apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-stateful-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-stateful-operator
  template:
    metadata:
      labels:
        name: hello-stateful-operator
    spec:
      containers:
        - name: hello-stateful-operator
          image: joatmon08/hello-stateful-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - hello-stateful-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "hello-stateful-operator"
